name: 'The Community Enrichment Project '
favicon: null
layout_spectrum: 0.33116
typography_spectrum: 0.08809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4e4e4e'
    - '#7eb574'
    - '#7e7e7e'
    - '#dadada'
  brandStrength: 1
  lightness: 0.8595321683678776
  saturation: 0.5465795078780502
  rhythmicContrast: 0.8904074523597956
purpose: []
